# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 472f1575c9915ee35d798b027beaea41f75898a78cce70f5f9f00f5eddef86e85813d29fb1e442850b7eab5b551eb906c6f48cfd36daa81447bc4c68a5eb6cb3

test:
  secret_key_base: 4d49fdaf6cc6138f376a1814e8dca3b3cada6a3641919d5e8f8f48e64cd4b310dd94a72864e942dccbedb12a6c25e8b1dd9c291011f9cb2999516bed45f7a52a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
